#..............................................................................
#.HHHH...HHHH.........................................OOOOOOO......SSSSSSS.....
#.HHHH...HHHH........................................OOOOOOOOOO...OSSSSSSSS....
#.HHHH...HHHH.......................................eOOOOOOOOOOO..OSSSSSSSSS...
#.HHHH...HHHH....oooooo..ommmmmmmmmmmmm....eeeeee...eOOOO..OOOOO.OOSSS..SSSS...
#.HHHH...HHHH..ooooooooo.ommmmmmmmmmmmmm..eeeeeeee.eeOOO....OOOOOOOSSS.........
#.HHHHHHHHHHH..oooo.oooooommmm.mmmmmmmmm.meee.eeee.eeOO......OOOO.OSSSSSS......
#.HHHHHHHHHHH.Hooo...ooooommm..mmmm..mmmmmeee..eeeeeeOO......OOOO..SSSSSSSSS...
#.HHHHHHHHHHH.Hooo...ooooommm..mmmm..mmmmmeeeeeeeeeeeOO......OOOO....SSSSSSS...
#.HHHH...HHHH.Hooo...ooooommm..mmmm..mmmmmeeeeeeeeeeeOOO....OOOOO.......SSSSS..
#.HHHH...HHHH.Hooo...ooooommm..mmmm..mmmmmeee.......eOOOO..OOOOO.OOSS....SSSS..
#.HHHH...HHHH..oooo.oooooommm..mmmm..mmmmmeee..eeee.eOOOOOOOOOOO.OOSSSSSSSSSS..
#.HHHH...HHHH..ooooooooo.ommm..mmmm..mmmm.eeeeeeee...OOOOOOOOOO...OSSSSSSSSS...
#.HHHH...HHHH....oooooo..ommm..mmmm..mmmm..eeeeee......OOOOOO......SSSSSSSS....
#..............................................................................
# +----------------------------------------------------------------------------+
# | Description:                                                               |
# | This is the main file for the HomeOS dashboard                             |
# +----------------------------------------------------------------------------+
# | Author: Sebastien Logeais                                                  |
# +----------------------------------------------------------------------------+
# | Date: 21 October 2023                                                      |
# +----------------------------------------------------------------------------+


# ==============================================================================
# |          ====> THIS IS THE SECTION TO CHANGE YOUR ENTITY  <=====           |
# | Change only 'xxxx.xxxx '                                                   |
# ==============================================================================
homeos_configuration:

# Apps Bar
# +----------+--------------------+-------------------------------------------+
# | Name     | Anchor Name        | Entity or icon svg to change              |
# +----------+--------------------+-------------------------------------------+
  climate:    &config_climate       'climate.entryway'
  alarm:      &config_alarm         'alarm_control_panel.alarmo'
  apps1:      &config_apps1         'group.docker_update'
  apps1_icon: &config_apps1_icon    '/local/homeos/appsbar_media/icon_docker.jpg'


# Scene Configuration
# +---+---+
# | 1 | 2 |
# +---+---+
# | 3 | 4 |
# +---+---+
#
# +----------+--------------------+-------------------------------------------+
# | Name     | Anchor Name        | Entity or icon svg to change              |
# +----------+--------------------+-------------------------------------------+
  scene1:       &config_scene1       'input_boolean.homeos_scene_clara_aux_dodo'
  scene1_icon:  &config_scene1_icon  'icon_moon_stars_fill'

  scene2:       &config_scene2       'input_boolean.homeos_scene_invite'
  scene2_icon:  &config_scene2_icon  'icon_wineglass_fill'

  scene3:       &config_scene3        'input_boolean.homeos_scene_morning_coffee'
  scene3_icon:  &config_scene3_icon   'icon_cup_saucer_fill'

  scene4:       &config_scene4        'input_boolean.homeos_scene_morning_coffee'
  scene4_icon:  &config_scene4_icon   'icon_empty'


# Garbage Card Configuration
  garbage:      &config_garbage       'schedule.garbage'
  recyling:     &config_recycling     'schedule.recycle'


# Person Card 
  person_bus:   &config_person_bus    'person.lynn'
  bus_route:    &config_bus_route     'sensor.491_express_est'


# ==============================================================================
# | Do not change code after this box                                          |
# ==============================================================================


kiosk_mode:
  hide_header: true

# all relevant template will be find
button_card_templates: !include_dir_merge_named homeos_module/

views:
# +----------------------------------------------------------------------------+
# | Definition of the first grid-layout                                        |
# | +------+----------------------------------+                                |
# | |      |           2 topbar               |                                |
# | |   1  +----------------------------------+                                |
# | | Apps |                                  |                                |
# | |      |           3 grid                 |                                |
# | |      |                                  |                                |
# | +------+----------------------------------+                                |
# +----------------------------------------------------------------------------+
  - type: custom:grid-layout
    title: HomeOS
    background: var(--background)
    layout:
      height: var(--homeos-screen-height)
      margin: 0
      grid-template-columns: var(--homeos-appsbar-width) 1fr 
      grid-template-rows: var(--homeos-topbar-height) 1fr 
      grid-gap: 0
      grid-template-areas: |
        "apps topbar "
        "apps cards"
    cards:

# +---+------------------------------------------------------------------------+
# | 1 | Definition of the Apps Bar                                             |
# +---+------------------------------------------------------------------------+
      - type: picture-elements
        view_layout:
          grid-area: apps  
        image: /local/homeos/empty.png
        style: |
          ha-card {
            border-radius: 0;
            border-top-left-radius: var(--homeos-card-border-radius);
            border-bottom-left-radius: var(--homeos-card-border-radius);
            --ha-card-background: var(--homeos-card-background);
            backdrop-filter: var(--homeos-card-backdrop-filter);
            --ha-card-border-color: rgba(0, 0, 0, 0);
            --ha-card-border-width: 0px;
          }
          :host {
            height: var(--homeos-screen-height);
            margin: 0px !important;
          }
        elements:

# +----------------------------------------------------------------------------+
# | Element are placed in order from top to bottom of the screen               |
# +----------------------------------------------------------------------------+       
          - type: custom:button-card
            entity: *config_climate
            template: template_climate
            style:
              top: 3vw
              left: calc(var(--homeos-appsbar-width) / 2 + 0.3vw)

          - type: custom:button-card
            entity: *config_alarm
            template:
              - icon_shield_fill
              - template_system_icon
            style:
              left: calc(var(--homeos-appsbar-width) / 2)
              top: 8vw
            styles: # Override normal setting to make the icon smaller
              custom_fields:
                icon: 
                  - width: calc( var(--homeos-appsbar-width) - 2.5vw)
     
          - type: custom:hui-element
            card_type: vertical-stack
            style:
              top: 30vw
              left: calc(var(--homeos-appsbar-width) / 2)
            cards:

              # Separator
              # - type: custom:button-card
              #   template: template_apps_separator

              - type: custom:button-card
                entity: *config_apps1
                entity_picture: *config_apps1_icon
                template:
                  - template_apps_icon

          - type: custom:button-card
            style:
              left: calc(var(--homeos-appsbar-width) / 2)
              top: 55vw
            styles: # Override normal setting to make the icon bigger
              custom_fields:
                icon: 
                  - width: calc( var(--homeos-appsbar-width) - 1.5vw)
            template:
              - icon_setting_fill
              - template_system_icon
            tap_action: !include homeos_module/appsbar/appsbar_setting_popup.yaml
              
          - type: custom:button-card
            style:
              left: calc(var(--homeos-appsbar-width) / 2)
              top: 60vw
            template:
              - icon_gearshape_fill
              - template_system_icon
            tap_action:
              action: navigate
              navigation_path: /config/integrations/dashboard

# +---+------------------------------------------------------------------------+
# | 2 | Definition of the top Bar                                              |
# +---+------------------------------------------------------------------------+    
      - type: custom:layout-card
        layout_type: custom:grid-layout
        view_layout:
          grid_area: topbar
        layout:
          card_margin: 0
          grid-template-columns: 1fr 12vw
          grid-template-rows: 1fr 
          grid-gap: 0
          margin: 0
          padding: 0
          grid-template-areas: |
            "notification xtime"
        cards:
          - type: custom:button-card
            view_layout:
              grid_area: notification
            entity: sensor.time
            show_state: true
            show_icon: false
            show_name: false
            style: |
              :host {
                margin: 0px !important;
              }
            styles:
              card:
                - background: rgba(0,0,0,0)
                - padding: 0
              state:
                - color: white
                - font-size: 2vw
                - mix-blend-mode: overlay
              custom_fields:
                overlay_effect:
                  - position: absolute
                  - display: flex
                  - font-size: 2vw
                  - transform: translate(0,0)
                  - justify-self: center

          - type: custom:button-card
            view_layout:
              grid_area: xtime
            entity: sensor.time
            show_state: true
            show_icon: false
            show_name: false
            style: |
              :host {
                margin: 0px !important;
              }
            styles:
              card:
                - background: rgba(0,0,0,0)
                - padding: 0
                - border-color: rgba(0,0,0,0)
                - height: var(--homeos-topbar-height)
              state:
                - color: rgba(240,240,240,0.2)
                - font-size: 3vw
              custom_fields:
                layer_1:
                  - position: absolute
                  - display: flex
                  - font-size: 3vw
                  - mix-blend-mode: overlay
                  - transform: translate(0,0)
                  - color: white
                  - justify-self: center
                layer_2:
                  - position: absolute
                  - display: flex
                  - font-size: 3vw
                  - transform: translate(0,0)
                  - mix-blend-mode: overlay
                  - color: white
                  - justify-self: center 
            custom_fields:
              layer_1: >
                [[[ return entity.state ]]]
              layer_2: >
                [[[ return entity.state ]]]                


# +---+------------------------------------------------------------------------+
# | 3 | Definition of the second custom grid layout                            |
# +---+------------------------------------------------------------------------+
      - type: custom:mod-card
        style: |
          :host {
            margin: 0px !important;
          }
        card:
          type: custom:layout-card
          layout_type: custom:grid-layout
          view_layout:
            grid_area: cards
          layout:
            card_margin: 0px
            height: calc( var(--homeos-screen-height) - var(--homeos-topbar-height) - 2*(var(--homeos-card-grid-gap)))
            grid-template-columns: repeat(8,var(--homeos-card-grid-square))
            grid-template-rows: repeat(5,var(--homeos-card-grid-square))
            grid-gap: var(--homeos-card-grid-gap)
            margin: 0
            padding: var(--homeos-card-grid-gap)
            grid-template-areas: |
              "weather  weather  map map map map scene person_bus"
              "weather  weather  map map map map 2 ."
              "weather  weather  map map map map 3 ."
              "calendar calendar map map map map 4 ."
              "calendar calendar garbage washer . . 5 ."

          cards:
# +----------------------------------------------------------------------------+
# | Weather Area Definition                                                    |
# +----------------------------------------------------------------------------+
            - type: custom:mod-card 
              view_layout:
                grid-area: weather
              # the following style ensure the card resize to the grid
              style: |
                ha-card {
                  display: contents;   
                }
                :host {
                  margin: 0px !important;
                }
              card: !include homeos_module/weather/weather_card.yaml  
    
# +----------------------------------------------------------------------------+
# | Calendar Area Definition                                                   |
# +----------------------------------------------------------------------------+
            - type: custom:mod-card
              view_layout:
                grid-area: calendar
              style: |
                ha-card {
                  display: contents;   
                }
                :host {
                  margin: 0px !important;
                }
              card: !include homeos_module/calendar/calendar_card.yaml

# +----------------------------------------------------------------------------+
# | Map Area Definition                                                        |
# +----------------------------------------------------------------------------+
            - type: custom:mod-card
              view_layout:
                grid-area: map
              style: |
                ha-card {
                  display: contents;   
                }
                :host {
                  margin: 0px !important;
                }
              card: !include homeos_module/map/map_card.yaml      

# +----------------------------------------------------------------------------+
# | Scene Area Definition                                                      |
# +----------------------------------------------------------------------------+
            - type: custom:mod-card
              view_layout:
                grid-area: scene
              style: |
                ha-card {
                  background: var(--homeos-card-background);
                  backdrop-filter: var(--homeos-card-backdrop-filter);
                  border-radius: var(--homeos-card-border-radius);
                  box-shadow: var(--homeos-card-box-shadow);
                  border-style: var(--homeos-card-border-style);
                  border-color: var(--homeos-card-border-color);
                  border-width: 1px;
                
                  --grid-card-gap: 0.8vw !important;
                  padding: 0.8vw;
                }
                :host {
                  margin: 0px !important;
                }
              card:
                  type: grid
                  columns: 2
                  cards:
                    - type: custom:button-card
                      entity: *config_scene1
                      template:
                        - *config_scene1_icon
                        - template_scene

                    - type: custom:button-card
                      entity: *config_scene2
                      template:
                        - *config_scene2_icon
                        - template_scene

                    - type: custom:button-card
                      entity: *config_scene3
                      template:
                        - *config_scene3_icon
                        - template_scene

                    - type: custom:button-card
                      entity: *config_scene4
                      template:
                        - *config_scene4_icon
                        - template_scene

               
# +----------------------------------------------------------------------------+
# | Garbage Area Definition                                                    |
# +----------------------------------------------------------------------------+
            - type: custom:mod-card
              view_layout:
                grid-area: garbage
              style: |
                ha-card {
                  --grid-card-gap: var(--homeos-card-grid-gap) !important; 
                }
                :host {
                  margin: 0px !important;
                }
              card:
                type: vertical-stack
                cards:
                  - type: custom:button-card     
                    entity: *config_garbage
                    template:
                      - template_garbage
                      - icon_trash_fill

                  - type: custom:button-card     
                    entity: *config_recycling
                    template:
                      - template_garbage
                      - icon_arrow3_trianglepath
        
# +----------------------------------------------------------------------------+
# | Map Area Definition                                                        |
# +----------------------------------------------------------------------------+
            - type: custom:mod-card
              view_layout:
                grid-area: washer
              style: |
                ha-card {
                  display: contents;   
                }
                :host {
                  margin: 0px !important;
                }
              card: !include homeos_module/washer_dryer/washer_dryer_card.yaml     
          
# +----------------------------------------------------------------------------+
# | Person in Bus Area Definition                                              |
# +----------------------------------------------------------------------------+

            - type: custom:mod-card
              view_layout:
                grid-area: person_bus
              style: |
                ha-card {
                  display: contents;   
                }
                :host {
                  margin: 0px !important;
                }             
              card:
                  type: custom:button-card
                  entity: *config_person_bus
                  variables:
                    bus_sensor: *config_bus_route
                  triggers_update: *config_bus_route
                  template:
                    - template_person_bus
                    - icon_bus_fill
