# +----------------------------------------------------------------------------+
# | This selection variable is use to define what theme to show (light/dark)   |
# | The automated system is based on the phone or computer settings.           |
# | In my case there is no dark and light with my fireHD tablet and I prefer   |
# | to use the Sun integration                                                 |
# +----------------------------------------------------------------------------+
input_select:
  homeos_theme_selection:
    name: HomeOS Theme Selection
    options: 
      - homeos_light
      - homeos_dark
    icon: mdi:theme-light-dark

sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "time_date"


# +----------------------------------------------------------------------------+
# | AUTOMATION                                                                 |
# +----------------------------------------------------------------------------+
automation:

# +----------------------------------------------------------------------------+
# | Description:                                                               |
# | This create the automation to change from Dark to Day theme                |
# | I don't use the default system because it doesn't work well with all tablet|
# +----------------------------------------------------------------------------+
  - alias: HomeOS Theme Night
    description: ''
    mode: single
    trigger:
      - platform: state
        entity_id:
        - sun.sun
        from: above_horizon
        to: below_horizon
      - platform: state
        entity_id:
        - input_select.homeos_theme_selection
        from: homeos_light
        to: homeos_dark

    condition: []
    action:
      - service: frontend.set_theme
        data:
          mode: dark
          name: homeos
      - service: browser_mod.set_theme
        data:
          dark: dark
        target:
          entity_id: binary_sensor.wall_tablet_browser_dark_mode
      - service: input_select.select_option
        data:
          option: homeos_dark
        target:
          entity_id: input_select.homeos_theme_selection

  - alias: HomeOS Theme Light
    description: ''
    mode: single
    trigger:
      - platform: state
        entity_id:
        - sun.sun
        to: above_horizon
        from: below_horizon
      - platform: state
        entity_id:
        - input_select.homeos_theme_selection
        from: homeos_dark
        to: homeos_light
    condition: []
    action:
      - service: frontend.set_theme
        data:
          mode: light
          name: homeos
      - service: browser_mod.set_theme
        data:
          dark: light
        target:
          entity_id: binary_sensor.wall_tablet_browser_dark_mode
      - service: input_select.select_option
        data:
          option: homeos_light
        target:
          entity_id: input_select.homeos_theme_selection