# +----------------------------------------------------------------------------+
# | HOME ASSISTANT PACKAGE                                                     |
# +----------------------------------------------------------------------------+
# | Package name: topbar.yaml                                                  |
# +----------------------------------------------------------------------------+
# | Author: Sebastien Logeais                                                  |
# | Date: 28 December 2023                                                     |
# +----------------------------------------------------------------------------+
# | Description:                                                               |
# | This package contain all entities and value template related to the        |
# | all topbar card.                                                           |
# +----------------------------------------------------------------------------+

# +----------------------------------------------------------------------------+
# | Lights Group                                                               |
# +----------------------------------------------------------------------------+
# | Integration instruction:                                                   |
# | 1. Change the entities you want to count ON/OFF                            |
# +----------------------------------------------------------------------------+
group:
  all_light:
    name: All light (switch and Light)
    entities:
      # Homekit integration 
      - light.ambientlightbedroomclara_lightbulb
      - light.leviton_dimmer_164a98
      - switch.smartplug_clara
      - switch.switch_exterieurback_switch
      - switch.switch_vestibule_switch
      # Govee Integration
      - light.dreamview_t1
      # MQTT Integration
      - light.dimmer_diningroom_shelly_dimmer_2
      - light.lamp_livingroomentry
      - light.light_bedclarabedroom
      - light.lightstairs_zigbeegroup
      - switch.switch_basement
      # TP-Link Kasa Integration
      - light.droite
      - light.lampe_gauche
      - light.clarabedroom
      - switch.prise_exterieur
      - switch.switch_exteriorfront
      # Wiz Integration
      - light.wiz_rgbw_tunable_6261a4
      # WLED Integration
      - light.wled

sensor:
# +----------------------------------------------------------------------------+
# | Temperature                                                                |
# +----------------------------------------------------------------------------+
# | Integration instruction:                                                   |
# | 1. Add after entity_ids which entities should be use to determine the min  |
# |    and the max temperature                                                 |
# +----------------------------------------------------------------------------+
  - platform: min_max
    name: temperature_min
    type: min
    entity_ids:
      - sensor.temperaturesensor_basement_temperature
      - sensor.temperaturesensor_clarabedroom_temperature
      - sensor.temperaturesensor_masterbedroom_temperature
      - sensor.temperaturesensor_office_temperature
      - sensor.temperaturesensor_upperbathroom_temperature

  - platform: min_max
    name: temperature_max
    type: max
    entity_ids:
      - sensor.temperaturesensor_basement_temperature
      - sensor.temperaturesensor_clarabedroom_temperature
      - sensor.temperaturesensor_masterbedroom_temperature
      - sensor.temperaturesensor_office_temperature
      - sensor.temperaturesensor_upperbathroom_temperature

  - platform: template
    sensors:
      temperature_min_max:
        friendly_name: Température
        value_template: "{{ states('sensor.temperature_min') | round(1) }} - {{ states('sensor.temperature_max') | round(1) }}°"

# +----------------------------------------------------------------------------+
# | Humidity                                                                   |
# +----------------------------------------------------------------------------+
# | Integration instruction:                                                   |
# | 1. Add after entity_ids which entities should be use to determine the min  |
# |    and the max humidity                                                    |
# +----------------------------------------------------------------------------+
  - platform: min_max
    name: humidity_min
    type: min
    entity_ids:
      - sensor.temperaturesensor_basement_humidity
      - sensor.temperaturesensor_clarabedroom_humidity
      - sensor.temperaturesensor_masterbedroom_humidity
      - sensor.temperaturesensor_office_humidity
      - sensor.temperaturesensor_upperbathroom_humidity

  - platform: min_max
    name: humidity_max
    type: max
    entity_ids:
      - sensor.temperaturesensor_basement_humidity
      - sensor.temperaturesensor_clarabedroom_humidity
      - sensor.temperaturesensor_masterbedroom_humidity
      - sensor.temperaturesensor_office_humidity
      - sensor.temperaturesensor_upperbathroom_humidity

  - platform: template
    sensors:
      humidity_min_max:
        friendly_name: Humidité
        value_template: "{{ states('sensor.humidity_min') | round(0) }} - {{ states('sensor.humidity_max') | round(0) }}%"

# +----------------------------------------------------------------------------+
# | Light                                                                      |
# +----------------------------------------------------------------------------+
# | Integration instruction:                                                   |
# | 1. Nothing to change here                                                  |
# +----------------------------------------------------------------------------+
  - platform: template
    sensors:
      lights_on_count:
        friendly_name: "Lumières"
        value_template: "{{ expand('group.all_light') | selectattr('state','eq','on') | list | count }} lumières allumées"

# +----------------------------------------------------------------------------+
# | Security                                                                   |
# +----------------------------------------------------------------------------+
# | Integration instruction:                                                   |
# | 1. Change the entity in the value template by your own alarm system        |
# +----------------------------------------------------------------------------+
  - platform: template
    sensors:
      security_status:
        friendly_name: Sécurité
        value_template: >
          {% if is_state('alarm_control_panel.alarmo', 'disarmed') %}
            Désactivé
          {% else %}
            Activé
          {% endif %}

# +----------------------------------------------------------------------------+
# | Battery                                                                    |
# +----------------------------------------------------------------------------+
# | Integration instruction:                                                   |
# | 1. Add after entity_ids which entities should be use to determine the min  |
# |    and the max of the batteries pourcentage                                |
# +----------------------------------------------------------------------------+
  - platform: min_max
    name: battery_min
    type: min
    entity_ids:
      - sensor.contactsensor_doorbasement_battery
      - sensor.contactsensor_dryer_battery
      - sensor.contactsensor_laundrycloset_battery
      - sensor.contactsensor_washingmachine_battery
      - sensor.cover_clarabedroom_battery
      - sensor.motionsensor_bottomstairs_battery
      - sensor.motionsensor_kitchen_battery
      - sensor.motionsensor_upperstairs_battery
      - sensor.motionsensor_vestibule_battery
      - sensor.remote1_clarabedroom_battery
      - sensor.remote_basement_battery
      - sensor.smokesensor_1stfloor_battery
      - sensor.smokesensor_basement1_battery
      - sensor.smokesensor_groundfloor_battery
      - sensor.temperaturesensor_basement_battery
      - sensor.temperaturesensor_clarabedroom_battery
      - sensor.temperaturesensor_masterbedroom_battery
      - sensor.temperaturesensor_office_battery
      - sensor.temperaturesensor_upperbathroom_battery
      - sensor.vibrationsensor_dryer_battery
      - sensor.watersensor_dishwasher_battery
      - sensor.watersensor_heater_battery
      - sensor.watersensor_washingmachine_battery

  - platform: min_max
    name: battery_max
    type: max
    entity_ids:
      - sensor.contactsensor_doorbasement_battery
      - sensor.contactsensor_dryer_battery
      - sensor.contactsensor_laundrycloset_battery
      - sensor.contactsensor_washingmachine_battery
      - sensor.cover_clarabedroom_battery
      - sensor.motionsensor_bottomstairs_battery
      - sensor.motionsensor_kitchen_battery
      - sensor.motionsensor_upperstairs_battery
      - sensor.motionsensor_vestibule_battery
      - sensor.remote1_clarabedroom_battery
      - sensor.remote_basement_battery
      - sensor.smokesensor_1stfloor_battery
      - sensor.smokesensor_basement1_battery
      - sensor.smokesensor_groundfloor_battery
      - sensor.temperaturesensor_basement_battery
      - sensor.temperaturesensor_clarabedroom_battery
      - sensor.temperaturesensor_masterbedroom_battery
      - sensor.temperaturesensor_office_battery
      - sensor.temperaturesensor_upperbathroom_battery
      - sensor.vibrationsensor_dryer_battery
      - sensor.watersensor_dishwasher_battery
      - sensor.watersensor_heater_battery
      - sensor.watersensor_washingmachine_battery

  - platform: template
    sensors:
      battery_min_max:
        friendly_name: Batteries
        value_template: "{{ states('sensor.battery_min') | round(0) }} - {{ states('sensor.battery_max') | round(0) }}%"



